env:
  global:
    - secure: SE2yzVIbCwL9pc0gLtai8ydxXsnF+eUETIGUfsXBJvUVsFYCY/slqFq0PZqMjwMBwoLM7KbGWQJi3/0RKbo45MXU0wo7JtdpqA0M2qrMJxBRwyAc6gA9GGfPPmX5C7evvcd+YTOgr5WRJwLP5ongn5DuTlkGeJy5dfqM8YDXNmeQ2pOU00KPtNs8Jw7m2SLg7Ib1CCFMPwfwIZY5eiavfK27a13Z1IZhs/UUYMWjb3iv31W1tXpLXf3NMNqW0Ppm992dgpNAMAy7sXE1PTseRddVhBwcqlyOD3MQZNW3+2Cue3zykLMIzDxfh+6jJJ5cpTyeitsMexzOSpL50/LFsuEb6Osdw9B86sisKqGcWBNkq4SOJRwGKtzm7kDHWoBp+FIv/HIZyy51xNk8V21ztlHg3Ht/OjsyV8xr9DvXcWHff3msfA9WpBt8d5F18/Y9TSK85jE2QSXSPMFVAgFtc1teGlHHI0RqJTCrzMopu1wH0XJUE1bnf1vqEHf5uJxKwUCRAs/C1xudk6/BqdtdtktLzePMlFZ/W1o0arOIwdYY/8FpRdXGO3TeYKH8awVA4c2KJDaBbgW/vFLj8mz8b8Q/fihg/xo6riMrKKXlYiw0u0IRGUcxODkT5kdG+hZtto393umJKrhhlegc4kfzcmiGrdzxIxTY6/YkrtBklCc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/SSH_attackers_probers
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
