env:
  global:
    - secure: YHz+0/e7WcOP5KAx+WolqF++NdauvN34QloDILc8SMm+HHI8+XhE9ZnmnJy5ZOd24aret+pAUjQAB7wmX7BQV+qrJtS8vZJQpvJoE3s+B+Vr0J+EkpuDOgdkY5NS+WryIHjUKDMrPaWLjQmSg+kyVqjMRu/dTN88JS84vlp3ncY/tNgBLhHTuDgZlaTZ0pWwPKPbYMBe6HiuzEkuOQ0YGbkf/09BbNKNZDUKAMrYR4VOO+ctmKMQXdn6rEnVfC4J6dUmplamn5G/bMlho5XMB+A+YadPMgPa15vBOKknInNXT+lmjkdwXEkiWv9z/ttEnESxDrittVSc852rq8XsAG1kVF9TzjvGVzzu81ayV/Av+JcR1Fl8S0zDi3feSFe/rkYIGniFC9/K2i1JBSj4p9U1KJRYwwAF6FnDaPLODPXQy1ycpJERHCaUYoDW5NuvmRaido9/WMkH3BIvUXf4M1YgItZfaRwsP+AQM6AHuScP6uaKmNBwucf9LL3DQrLPS36mHNgAb5837tbBDbApnqLcVaILJH5VaWkj7Qg0y2ScKC1vvAKoD7WlvYJ4vioZ5QuggrtEBO9a7qtapwq9hFJnqQ6QK0ZQg3TEr+Pt5Hqqe5uCXwEUMXPgM+/O/epIuBQqSbdaA0wmJCwets4zhXr1r7eADl2UFmvdFAZNyso=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/SSH_attackers_probers
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
