env:
  global:
    - secure: enaNOnfUZBTljZRDi5bcDorVm56P8C9kX1/tMqeBcbJ460DaAClBFxPRaA2CT352lsW2hBwsClkM9kcAWRe7K1o4fA4m6qTA9Ib3A7NHvtzth1Ym7qJy24CXk3cQi1tIxoFZmTawRFOIBLTRTYbrA6zJEh9hgtfuAfPmAJGSFGzPf/p9u7equZrsbHrZk2jDIiNsoQDnmcQrXVhEhjgSwQ0PkaO522p8dCMuGZ6e1akCDoyW7q+w3vV6qMYmJzFD8gYYiTqSiJBHuB5GlfIeARhyUMRORCq/suG/jti3BTjuMhHtaaZjEjFKK6g0lhZXlD2L0R4OWLBGyqS6a22t1iB+nzXSPFf9sxjxwjDZV7ob5xZCryG5nayM/StwLTMq1a4win4CoLGMwtWXKxSAIVwZXs0saT3fkOMzY/ALvzE3TnTYv9UrM+ql7G3sLAfeL+R1ZUaVmECiIb5YccFLgMxkt28oLhWx/EX3VVg/d3jdUz4Xz5RGbyVoYsx0eG794CgsKEf8xkRmPBGW6NTP9xyu0CjqoK8HOX6cMHHpYZZmZDkOL3RcwbrE+1ZpNw5N86IrV6+GGUG/7ybFAKDRNusNOrMGxX2OrhW3RdBahtg6QGXwMX+9awb1DykSs4Qm2icrdSR/4GrkuOnJ9gyTUzUSQZyS2qV6+geY7w2Xb9I=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/SSH_attackers_probers
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
