env:
  global:
    - secure: Ivio+f1npfceNM4AREzduKKQOPYN7V1fqaFKutpGRSae3nnylsAVabfOG/Y8fn3mF5PW9utom3/WDXuWmEUsC5XH0GYAGOENRbrMLPNtXYuaHT124Wfka9WTbw5Fu+R1K4/HxSKDGrOOpIJChpP1s2yfNSRYXLsY7hj21oYf/WksnszWzEBo51MzxvmcYMI46W9P8aTXPojuGU5StRKus3BIZv9+fAjyMKvEncgVlQ6lWs9pPmaxrr9xZmsOYeGLXNg3YzLgzSTzHb5ja3tyx/eiW4du8ImJoIbpiHagacfYv6egZUJBsvD9BGsQNgsoNYkYc3IxVxjZNF2eCIrE7dYxr+FO6ttVpjEXb8VWVm1Aib7RphiY625HzYIPiky0mrkAdsr2bgJyTBtWIW37TuCUp0eyRipIA2UGOKp/MHXIDY5WaQdGQk2ha7Z9L6mB3OdV4Z/QynL7TK0nowHy3RBBbuj6JAMlm0hFSWq+R2EGPF3fcGmaVx3Nwn+Mvez/9tbnPP7KKeU8Gv5tErSNl2QM/yWDSzGw1Koy2/0mGv7Dy1LiBAPALCxppZfaic7l3wdINUp+g+AetDD/59WuoQaIunQ1lqfD2jtheFuRR/l9p4MP6RYiEtnIAlnD68eqFSYzfx7TYledC7ioA2imdBmSi6jLq8CDthMsk+Jlnrw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/SSH_attackers_probers
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
