env:
  global:
    - secure: xAl3Qe08YUU55l8yPVTJmPAsW5mmUrhrVj/f7WG/wGiLdNSIwPs6mxx7VH3PQ4iW1G8R61VLbQ872VRcTfXqH7xZcCZTdREHkfDZYR5YN2DgdBkrf2B9Okg0UqyRBV2iVufiCSpnVZP/pgD5kHoE2zvm/27Jq0Wx/3qDGX7bTaBktauJlhC7ZD0+Y1c8RSodaQ33t9A1KhEDN5s3I/+zEYT2cwPYRaOt04/PzXu2w5WCs86Hkl0qiuEFW0iX9EuE3KdiRtqGzeQ89nne1KDsdFJBAqngvEwRp0VbqVx0CQyjQiZG3DFMwsoHrnD/fE6KoDTZmI56lr7k6BXj55MMtnWdKj2zR4UgF0xN7K1gJLbx0RPdPOv4heKtmgfcj11SInNAlYXIA+UGgRh689+TnBVOVCNgr4diS06Ux4Ak5BKrTXMOgNxp2NVhOUejc0ubc/BvOtWxe3rZB+RKa0/AqLtYCFogz8jtZVj4FTIVWr6efiiGQ7UQ7ct4FYZ8kqKosFuMysCVc1MTx2c+jYLRohKW7ietjJNeIw0irgAc/E2NEFuodEf2tgXClHHqJTatj84Y+6bXl0wstVmMc0n7NEiQ+isIVVSE8qMYGRUFl0jiapJfcE7sowgGM6Zns0rtNeBviOxMuXxsFCOkl4wskHzqMoIcg38KMhRKg1wf/ec=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/SSH_attackers_probers
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
