env:
  global:
    - secure: j1Cq59vYufjZDsB4FpZ2oppNEQ4HpmOsJqprTcndAogJoIgcOUOPOHgaOR/9YNiRo7zXLBtllclL+eRRgf2JEA9QjJrn6ovDONyBxiwKK/DNPk+078QO+o3/9ZOkUmGpgtTNL+4UlEa++bL4EBt75UdSIKx8iZGrQkAXFL2s40AFwrh3bKC9XyeV9TQ2Q6Sx2hr/fm9W80faIJkuG/ilrOZo7nXv0cnXOzICUtGmaVkh5MyTV0D3mFlnL+eVl4HTLxgyXsawSyujpasGPXT0ZBd1TSjkucEz5MosFzdRiLrDuwEmaoeMWljggSf55UuZey14G4udwkCNVlD1zk7BXTEVcdvutMP7LUl35cmH8lUvGGd1LZJUlCTDs4l9T4GZyWbMbzdtf4N7MZSpGQ7tvluQlGO8b1QvBfLTlAaMS9D2c8k45El0ZKW425LcVx2kWW6ZbnXHAkR8HJRiS81/aXdguPuMF58haRonWZIsXtXGbaViErxU0+A2qTmO0agSWqc57cFwfFdVwd+xNz/c4EI3LPP5pYCJ1yW0kp884431quZKumkF7Gw3h/u42q1PxYetVYpeRdqPfiA9vPVLa8wvfmNZLTp8LBwYI4AbmsDX3d41QK0ewkz3anDdgqQRl47p+9Nu+7YSPD5wTSmTQROXubbd0BCu5GdM3VIFZCM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/SSH_attackers_probers
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
