env:
  global:
    - secure: 058mnuTRho84YCJP26cEY9kW8ietIRgl4vD8csrz3zSo+iV1LOnhnjqvQKrYF15ndMMSwEwMq5LXs3OacYke30rilpP5Gv2utpmr4XE5H437yabMhl0um0ejm5JVaNDtwG+uRTE/I5yZzb3zGeLm7N6gsJqVSc/4earOjdGwn6/aGa17JqMKzkay4154K+7Ezg0GkBBWsh6dkYOGqs8c9VYqoFWNTjiKMQK/twGpWzdhQy6AVMAUC4M6NbXCBaHC0eq+z+UWqL5Pgr55p8JoYqJKRwKJZXDwIORdwbZPWzAU7AWbeCdx33LkOknV1qbK3VgfwxP/uu+vMzm2c+YtbZVrU/GpJSfE3HE57PkPRv57LXX2Hx+y/ZbTtpMjdNEzj+1SXlCDsAVbU3GcS8bG1HQ09OTKw/+Zp7FuJluhWkBmR2PgwCpd4aM13thvqjcJZv/xb5iYFiN+v1zlE0Vtw4m7g/jbC59G6gZhfrT+9JN/pgQCFluPusiZsx2CzynVEnfP0hw3pLNc++ICiKHL4rF2qvWTKyp6nBktQ83KAkdVIvjNox9ysK6ALstI6CSexktFQ8l0NSs5iCtT8xUxozXG0lc2L474VLnyvHHpP2twRRpYDwR69EYuXsqyobOnNhtivdOEYNjSCmvUTbujK7m2RAMP7ceQ2IY9FJr3FA8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/SSH_attackers_probers
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
